
export const US_STATES = [
    { value: "AL", label: "Alabama" },
    { value: "AK", label: "Alaska" },
    { value: "AZ", label: "Arizona" },
    { value: "AR", label: "Arkansas" },
    { value: "CA", label: "California" },
    { value: "CO", label: "Colorado" },
    { value: "CT", label: "Connecticut" },
    { value: "DE", label: "Delaware" },
    { value: "FL", label: "Florida" },
    { value: "GA", label: "Georgia" },
    { value: "HI", label: "Hawaii" },
    { value: "ID", label: "Idaho" },
    { value: "IL", label: "Illinois" },
    { value: "IN", label: "Indiana" },
    { value: "IA", label: "Iowa" },
    { value: "KS", label: "Kansas" },
    { value: "KY", label: "Kentucky" },
    { value: "LA", label: "Louisiana" },
    { value: "ME", label: "Maine" },
    { value: "MD", label: "Maryland" },
    { value: "MA", label: "Massachusetts" },
    { value: "MI", label: "Michigan" },
    { value: "MN", label: "Minnesota" },
    { value: "MS", label: "Mississippi" },
    { value: "MO", label: "Missouri" },
    { value: "MT", label: "Montana" },
    { value: "NE", label: "Nebraska" },
    { value: "NV", label: "Nevada" },
    { value: "NH", label: "New Hampshire" },
    { value: "NJ", label: "New Jersey" },
    { value: "NM", label: "New Mexico" },
    { value: "NY", label: "New York" },
    { value: "NC", label: "North Carolina" },
    { value: "ND", label: "North Dakota" },
    { value: "OH", label: "Ohio" },
    { value: "OK", label: "Oklahoma" },
    { value: "OR", label: "Oregon" },
    { value: "PA", label: "Pennsylvania" },
    { value: "RI", label: "Rhode Island" },
    { value: "SC", label: "South Carolina" },
    { value: "SD", label: "South Dakota" },
    { value: "TN", label: "Tennessee" },
    { value: "TX", label: "Texas" },
    { value: "UT", label: "Utah" },
    { value: "VT", label: "Vermont" },
    { value: "VA", label: "Virginia" },
    { value: "WA", label: "Washington" },
    { value: "WV", label: "West Virginia" },
    { value: "WI", label: "Wisconsin" },
    { value: "WY", label: "Wyoming" }
]

export const CAR_MAKES = [
    "Toyota", "Honda", "Ford", "Chevrolet", "Nissan", "Hyundai", "Kia", "Tesla", "Volkswagen", "Subaru", "Jeep", "Mazda", "BMW", "Mercedes-Benz", "Audi", "Lexus", "Dodge", "Ram", "GMC", "Other"
]

export const CAR_YEARS = Array.from({ length: 30 }, (_, i) => (new Date().getFullYear() - i).toString())

export const POPULAR_MODELS: Record<string, string[]> = {
    "Toyota": ["Camry", "Corolla", "Prius", "RAV4", "Highlander", "Tacoma", "Sienna"],
    "Honda": ["Civic", "Accord", "CR-V", "Pilot", "Odyssey", "HR-V"],
    "Ford": ["F-150", "Escape", "Explorer", "Fusion", "Focus", "Mustang"],
    "Chevrolet": ["Silverado", "Equinox", "Malibu", "Traverse", "Tahoe", "Bolt EV"],
    "Nissan": ["Altima", "Sentra", "Rogue", "Versa", "Pathfinder"],
    "Hyundai": ["Elantra", "Sonata", "Tucson", "Santa Fe", "Kona", "Ioniq"],
    "Kia": ["Optima", "Forte", "Sorento", "Soul", "Sportage", "Telluride"],
    "Tesla": ["Model 3", "Model Y", "Model S", "Model X"],
    "Volkswagen": ["Jetta", "Passat", "Tiguan", "Atlas", "Golf"],
    "Subaru": ["Outback", "Forester", "Crosstrek", "Impreza", "Ascent"],
    "Jeep": ["Grand Cherokee", "Wrangler", "Cherokee", "Compass", "Renegade"],
    "Mazda": ["CX-5", "CX-30", "Mazda3", "CX-9"],
    "BMW": ["3 Series", "5 Series", "X3", "X5"],
    "Mercedes-Benz": ["C-Class", "E-Class", "GLC", "GLE"],
    "Audi": ["A4", "Q5", "A3", "Q7"],
    "Lexus": ["RX", "ES", "NX", "IS"],
    "Dodge": ["Charger", "Challenger", "Durango"],
    "Ram": ["1500", "2500"],
    "GMC": ["Sierra", "Terrain", "Acadia", "Yukon"]
}
